---
version: 3
images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest'
options:
  package_manager_path: /usr/bin/microdnf
dependencies:
  galaxy: requirements.yml
  python: requirements.txt

